# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/web/angular-wallet"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/desktop/wallet"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/scripts"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/scripts"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/lib"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "typedoc"
          version_requirement: "0.14.2"
